// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJgMNANHKDEJwTPm1RlAy8Zwy4pgDu_H4',
    appId: '1:836503754729:web:9477f3111e991be7f79d78',
    messagingSenderId: '836503754729',
    projectId: 'mynotes-ca63c',
    authDomain: 'mynotes-ca63c.firebaseapp.com',
    storageBucket: 'mynotes-ca63c.appspot.com',
    measurementId: 'G-2QMZ6CFYEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3asmpbYWuKWcS8q-GI6u7EoD6Dk-WmjM',
    appId: '1:836503754729:android:6f6c84c14a33e891f79d78',
    messagingSenderId: '836503754729',
    projectId: 'mynotes-ca63c',
    storageBucket: 'mynotes-ca63c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIr6yEo1ttPf7vzzdC2r_HrUnBXUKlKU',
    appId: '1:836503754729:ios:08198e6380c9c975f79d78',
    messagingSenderId: '836503754729',
    projectId: 'mynotes-ca63c',
    storageBucket: 'mynotes-ca63c.appspot.com',
    iosBundleId: 'com.example.myflutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIr6yEo1ttPf7vzzdC2r_HrUnBXUKlKU',
    appId: '1:836503754729:ios:0038ca91a51b06d0f79d78',
    messagingSenderId: '836503754729',
    projectId: 'mynotes-ca63c',
    storageBucket: 'mynotes-ca63c.appspot.com',
    iosBundleId: 'com.example.myflutterFirebaseFirestore.RunnerTests',
  );
}
